token: ${TOKEN}
ruleset_type: repo # or org
target_type: your_target_type
enforcement_type: your_enforcement_type
ruleset_name: your_ruleset_name
ruleset_properties:
  - key: key1
    value: value1
  - key: key2
    value: value2
  - key: key3
    value: value3
rules:
  - rule1
  - rule2
  - rule3